### ISSUE TITLE
Подскажите, как исправить проблему CORS

### ISSUE THREAD

**Issue by Gorbulev-Sergey** [a2seven/yoocheckout#15]
Залил тестовый сайт на Netlify (мой сайт: https://svelte-market-gorbulevsv.netlify.app), ssl подключен, пробую создать платёж, выдаёт ошибку:

`Access to XMLHttpRequest at 'https://api.yookassa.ru/v3/payments' from origin 'https://svelte-market-gorbulevsv.netlify.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by krom** [comment]
Вам надо
1. подключить библиотеку на бекэнде
2. С фронтенда отправлять запрос на собственный бэк
3. На сервере производить валидацию данных, сформировать запрос к yookassa
4. Обработать ответ от yookassa (обновить запись в БД и т.к.)
5. Отправить ссылку на оплату на фронтенд
6. Перейти на оплату, например, через window.open()


В вашем случае
1. Yookassa блокирует подобные обращения (точнее указывает браузеру блокировать)
2. Вы не управляете полноценно заказом
3. Ключи доступа зашиты на фронте и могут быть легко извлечены и использованы злоумышленником в своих целях

**Comment by Gorbulev-Sergey** [comment]
Огромное спасибо, krom, за ответ, теперь хотя бы буду знать всю последовательность действий (честно говоря первый раз пытаюсь подключить платёжную систему), конечно, хотелось обойтись без серверной части, но видно не судьба! Так понимаю, что нужно закрыть эту ветку.
