### ISSUE TITLE
Optional recepit fields phone and email are implemented as mandatory

### ISSUE THREAD

**Issue by Gaen** [a2seven/yoocheckout#5]
Receipt fields [phone](https://yookassa.ru/developers/api#create_payment_receipt_phone) and [email](https://yookassa.ru/developers/api#create_payment_receipt_email) are documented as optional but [implemented as mandatory](https://github.com/a2seven/yoocheckout/blob/dev/lib/types/IReceipt.ts#L7-L8).

**Comment by krom** [comment]
Fixed with version 1.1.4
