### ISSUE TITLE
Неправильный тип ключа "capture" в ICreatePayment interface

### ISSUE THREAD

**Issue by justficks** [a2seven/yoocheckout#6]
![image](https://user-images.githubusercontent.com/36725599/172838598-5b6f42b2-e851-4411-8b56-0c93bb2d7ba4.png)

[Из документации ](https://yookassa.ru/developers/api#create_payment), capture: boolean

<img width="687" alt="Screenshot 2022-06-09 at 12 44 56" src="https://user-images.githubusercontent.com/36725599/172839159-2758b997-abb9-4816-be32-79dffa1a9903.png">

**Comment by krom** [comment]
Исправлено в версии 1.1.4
